## Section A: Data Structures & Control Structures

1.Create a list of 5 integers. Perform and print the result of the following operations: append, extend, insert, remove, pop, clear, index, count, sort, and reverse.

In [56]:
## append
a=[1,3,4,5,6,7]
a.append(9)
a

[1, 3, 4, 5, 6, 7, 9]

In [57]:
## extend
a.extend([10,23,43])
a

[1, 3, 4, 5, 6, 7, 9, 10, 23, 43]

In [58]:
## insert
a.insert(4,33)
a

[1, 3, 4, 5, 33, 6, 7, 9, 10, 23, 43]

In [59]:
## remove
a.remove(7)
a

[1, 3, 4, 5, 33, 6, 9, 10, 23, 43]

In [60]:
## pop
a.pop()
a

[1, 3, 4, 5, 33, 6, 9, 10, 23]

In [61]:
## clear
a.clear()
a

[]

In [62]:
## index
b=[20,30,40,50,60]
print(b.index(40))

2

In [63]:
## count
c=[10,20,30,40,20,60,20]
print(c.count(20))

3

In [64]:
## sort
d=[20,10,40,30,50]
d.sort()
d

[10, 20, 30, 40, 50]

In [65]:
## reverse
e=[50,40,30,20,10]
e.reverse()
e

[10, 20, 30, 40, 50]

2.Create a tuple that stores 3 student names. Try changing the second name in the tuple. What happens? Explain why.

In [66]:
tuple=('charan','balu','thishan','giri')
tuple[1]='sai'

TypeError: 'tuple' object does not support item assignment

# what happens?

python is raises an error because tuples are immutable,so you cannot add ,remove and modify their elements after they are created.The second name cannot be changed because tuples are designed to be read only. If you need to modify the elements, use a list instead of a tuple.

3.Create a set of integers with some duplicate values. Print the set and explain the output.

In [67]:
set={1,2,3,4,5,5,4,3,2,1}
set

{1, 2, 3, 4, 5}

## Explanation

A set stores only unique values and also unordered
when duplicate values(1,2,3,4 and 5) are added. Python automatically removes the duplicates.

4.Create a dictionary with the keys: 'name', 'age', and 'city'. Update the age and add a new key 'email'. Print the final dictionary.

In [68]:
dict={'name':'charan','age':20,'city':'tirupati'}
dict['age']=21
dict['email']='ravillacharansai1234@gmail.com'
print(dict)

{'name': 'charan', 'age': 21, 'city': 'tirupati', 'email': 'ravillacharansai1234@gmail.com'}

5. Write a script that checks if a person is eligible to vote (age ≥ 18). Take age as a variable and print the appropriate message.

In [69]:
age=20
if age >= 20:
    print("Eligible to vote")
else:
    print("not eligible to vote")

Eligible to vote

6.Given a 'marks' variable, print the grade:
- 90 and above: 'A'
- 75–89: 'B'
- 50–74: 'C'
- Below 50: 'Fail'

In [70]:
marks=72
if marks >= 90:
    print('grade:A')
elif marks >= 75:
    print('grade:B')
elif marks >= 50:
    print('grade:C')
else:
    print('Fail')

grade:C

7.Given a number, check if it's positive, and if it is also even. If not positive, print if it's zero or negative.

In [71]:
numb = 8
if numb > 0:
    print("the number is positive")
    if numb % 2 == 0:
        print("the number is even")
    else:
        print("the number is odd")
elif numb == 0:
    print("the number is zero")
else:
    print("the number is negative")

the number is positive
the number is even

## Section B: Numpy

8.Create:
- A scalar using np.array(5)
- A 1D array with values 1 to 5
- A 2D array (2x3) with values from 10 to 60 in steps of 10

In [72]:
import numpy as np

In [73]:
scalar=np.array(5)
array_1d=np.arange(1,6)
array_2d=np.arange(10,61,10).reshape(2,3)
print("scalar:",scalar)
print("1d_array:",array_1d)
print("2d_array:",array_2d)

scalar: 5
1d_array: [1 2 3 4 5]
2d_array: [[10 20 30]
 [40 50 60]]

9.Generate a 4x4 Numpy array of random integers between 0 and 100 using np.random.randint().

In [74]:
array_2d=np.random.randint(0,101,16).reshape(4,4)
array_2d

array([[81, 38, 89, 54],
       [79, 91, 40, 92],
       [97, 84, 87, 98],
       [ 6, 91, 30, 51]], dtype=int32)

10.Create a 2D numpy array of shape (3x3). Convert it into a pandas DataFrame and add column names: 'A', 'B', 'C'.

In [75]:
array_2d=np.array([[2,3,4],[3,5,7],[4,8,1]])
array_2d

array([[2, 3, 4],
       [3, 5, 7],
       [4, 8, 1]])

In [76]:
import pandas as pd

In [77]:
da=pd.DataFrame(array_2d,columns=['A','B','C'])
da

   A  B  C
0  2  3  4
1  3  5  7
2  4  8  1

## Section C: Exploring Pandas

11.Create a small DataFrame manually with 10 rows and columns: 'Name', 'Age', 'City', and 'Salary'. Then:
- Use .info(), .describe()
- Select 'Name' and 'City' columns
- Drop 'City' column
- Fill any missing values in 'Salary' column with the mean
- Remove any duplicate rows

In [78]:
wa = {
    'name': ['sai', 'charan', 'balu', 'thishan', 'giri',
             'sasi', 'malli', 'viyaan', 'sreenu', 'ramu'],
    
    'age': [21, 22, 33, 44, 20, 55, 23, 32, 25, 30],
    
    'city': ['chennai', 'pune', 'tirupati', 'kadapa', 'hyderabad',
             'mumbai', 'annamaya', 'vizag', 'kakinada', 'bengaluru'],
    
    'salary': [20000, 30000, 40000, 24000, 33000,
               50000, 60000, 10000, 45000, 76000]
}

In [79]:
sa=pd.DataFrame(wa)
sa

      name  age       city  salary
0      sai   21    chennai   20000
1   charan   22       pune   30000
2     balu   33   tirupati   40000
3  thishan   44     kadapa   24000
4     giri   20  hyderabad   33000
5     sasi   55     mumbai   50000
6    malli   23   annamaya   60000
7   viyaan   32      vizag   10000
8   sreenu   25   kakinada   45000
9     ramu   30  bengaluru   76000

In [80]:
sa.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   name    10 non-null     object
 1   age     10 non-null     int64
 2   city    10 non-null     object
 3   salary  10 non-null     int64
dtypes: int64(2), object(2)
memory usage: 452.0+ bytes

In [81]:
sa.describe()

            age        salary
count  10.00000     10.000000
mean   30.50000  38800.000000
std    11.30634  19752.918209
min    20.00000  10000.000000
25%    22.25000  25500.000000
50%    27.50000  36500.000000
75%    32.75000  48750.000000
max    55.00000  76000.000000

In [82]:
sa[['name','city']]

      name       city
0      sai    chennai
1   charan       pune
2     balu   tirupati
3  thishan     kadapa
4     giri  hyderabad
5     sasi     mumbai
6    malli   annamaya
7   viyaan      vizag
8   sreenu   kakinada
9     ramu  bengaluru

In [83]:
sa.drop(columns=['city'])

      name  age  salary
0      sai   21   20000
1   charan   22   30000
2     balu   33   40000
3  thishan   44   24000
4     giri   20   33000
5     sasi   55   50000
6    malli   23   60000
7   viyaan   32   10000
8   sreenu   25   45000
9     ramu   30   76000

In [84]:
salary_mean=sa['salary'].mean()
sa['salary']=sa['salary'].fillna(salary_mean)
print(sa)

      name  age       city  salary
0      sai   21    chennai   20000
1   charan   22       pune   30000
2     balu   33   tirupati   40000
3  thishan   44     kadapa   24000
4     giri   20  hyderabad   33000
5     sasi   55     mumbai   50000
6    malli   23   annamaya   60000
7   viyaan   32      vizag   10000
8   sreenu   25   kakinada   45000
9     ramu   30  bengaluru   76000

In [85]:
sa.drop_duplicates()

      name  age       city  salary
0      sai   21    chennai   20000
1   charan   22       pune   30000
2     balu   33   tirupati   40000
3  thishan   44     kadapa   24000
4     giri   20  hyderabad   33000
5     sasi   55     mumbai   50000
6    malli   23   annamaya   60000
7   viyaan   32      vizag   10000
8   sreenu   25   kakinada   45000
9     ramu   30  bengaluru   76000